// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0wYq-jhzyACixkL7oho6md0RTJV1lqNU',
    appId: '1:965917654008:web:b5bac87ae68aa6b634f40d',
    messagingSenderId: '965917654008',
    projectId: 'moments-be67f',
    authDomain: 'moments-be67f.firebaseapp.com',
    storageBucket: 'moments-be67f.appspot.com',
    measurementId: 'G-HQ3K1L4LZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0sS83uIgQSeNs_nogdX4xC2lIrQ4kHhc',
    appId: '1:965917654008:android:30b43fd7ad02e4c434f40d',
    messagingSenderId: '965917654008',
    projectId: 'moments-be67f',
    storageBucket: 'moments-be67f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkTkeqC1HxRMyY-zPiYTnqHK7q9FYJEVQ',
    appId: '1:965917654008:ios:34a5abb7a9ee87eb34f40d',
    messagingSenderId: '965917654008',
    projectId: 'moments-be67f',
    storageBucket: 'moments-be67f.appspot.com',
    androidClientId: '965917654008-up4em6blf8ei7msh7m1pjl98f8oftgho.apps.googleusercontent.com',
    iosClientId: '965917654008-r5docn0gkpkh49v7tllpkb62tfng35rc.apps.googleusercontent.com',
    iosBundleId: 'com.momentschain.moments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkTkeqC1HxRMyY-zPiYTnqHK7q9FYJEVQ',
    appId: '1:965917654008:ios:34a5abb7a9ee87eb34f40d',
    messagingSenderId: '965917654008',
    projectId: 'moments-be67f',
    storageBucket: 'moments-be67f.appspot.com',
    androidClientId: '965917654008-up4em6blf8ei7msh7m1pjl98f8oftgho.apps.googleusercontent.com',
    iosClientId: '965917654008-r5docn0gkpkh49v7tllpkb62tfng35rc.apps.googleusercontent.com',
    iosBundleId: 'com.momentschain.moments',
  );
}
